version: "3"

services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl-panel
    restart: always
    environment:
      - APP_URL=http://localhost
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=panel
      - DB_USERNAME=pterodactyl
      - DB_PASSWORD=supersecret
    volumes:
      - ./panel-data:/app/var
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.5
    container_name: pterodactyl-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD=rootpassword
      MYSQL_DATABASE=panel
      MYSQL_USER=pterodactyl
      MYSQL_PASSWORD=supersecret
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: pterodactyl-redis
    restart: always
